name: AutoMerge
on:
  check_suite:
    types:
      - completed
jobs:
  worker:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == "success"
      # github.actor == "dependabot[bot]" && 
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(JSON.stringify(context, null, 2));
# github.pullRequests.merge({
#   owner: context.payload.repository.owner.login,
#   repo: context.payload.repository.name,
#   pull_number: context.payload.pull_request.number
# })
